### ISSUE TITLE
Wrong character coding in parts of the applications

### ISSUE THREAD

**Issue by seledun** [JakobEdvardsson/poker-game#6]
Some parts of the application have trouble showing 'åäö' characters which are part of the Swedish translation.

![bild](https://github.com/JakobEdvardsson/poker-game/assets/64317746/87d128fd-b205-40a3-a758-5d1bf72f996c)
![bild](https://github.com/JakobEdvardsson/poker-game/assets/64317746/d9d76c71-e448-4a15-ba4d-8881cec9a150)

This problem however does __not__ show in the Rules pane.

![bild](https://github.com/JakobEdvardsson/poker-game/assets/64317746/601c0e4b-9c97-428d-be13-0d3a517dcf7e)

**Comment by Dautabossy** [comment]
![Image](https://github.com/JakobEdvardsson/poker-game/assets/114819894/c15486b7-cb05-4aa0-8c68-98ca3b922c38)
